In [1]:
import tensorflow as tf
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
training_set = tf.keras.utils.image_dataset_from_directory(
    "D:/sudesh/projects/plant desies detection/archive (4)/Train/Train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 1322 files belonging to 3 classes.


In [3]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    "D:/sudesh/projects/plant desies detection/archive (4)/Validation/Validation",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 60 files belonging to 3 classes.


In [4]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[211.94531  235.94531  235.94531 ]
   [215.       239.       239.      ]
   [213.875    237.875    237.875   ]
   ...
   [111.       145.        68.      ]
   [108.6875   145.6875    68.6875  ]
   [103.94531  140.94531   63.945312]]

  [[217.35156  236.35156  241.60156 ]
   [219.       239.375    243.9375  ]
   [215.50781  239.50781  242.75781 ]
   ...
   [113.       148.        66.      ]
   [110.6875   147.6875    68.4375  ]
   [107.21094  144.21094   64.96094 ]]

  [[219.       236.       244.      ]
   [220.3125   238.6875   246.      ]
   [220.       240.       249.      ]
   ...
   [115.88281  150.88281   68.88281 ]
   [113.       150.        70.      ]
   [108.375    145.375     65.375   ]]

  ...

  [[107.21094  147.21094  110.21094 ]
   [106.57031  146.57031  109.57031 ]
   [104.44531  144.44531  109.44531 ]
   ...
   [151.64844  173.       141.88281 ]
   [144.60938  169.       132.80469 ]
   [132.77344  163.77344  121.77344 ]]

  [[109.27344  146.27344  112.2734

In [5]:
from tensorflow.keras.layers import Dense,Conv2D,Flatten,MaxPool2D,Dropout
from tensorflow.keras.models import Sequential

In [6]:
model = Sequential()

In [7]:
# making cnn
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[256,256,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

C:\Users\Komal Patil\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
# making cnn
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [9]:
# making cnn
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [10]:
# making cnn
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [11]:
# making cnn
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [12]:
model.add(Dropout(0.25))

In [13]:
model.add(Flatten())

In [14]:
model.add(Dense(units=1500,activation='relu'))

In [15]:
#output layer
model.add(Dense(units=3,activation='softmax'))

In [16]:
model.compile(optimizer= tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 256, 256, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 254, 254, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 127, 127, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 127, 127, 64)        │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 125, 125, 64)        │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 62, 62, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 62, 62, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 60, 60, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 30, 30, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 30, 30, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 28, 28, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 14, 14, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 14, 14, 512)         │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 12, 12, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 6, 6, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 6, 6, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 18432)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1500)                │      27,649,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 3)                   │           4,503 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 32,366,227 (123.47 MB)

 Trainable params: 32,366,227 (123.47 MB)

 Non-trainable params: 0 (0.00 B)

In [18]:
# training model

In [19]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
42/42 ━━━━━━━━━━━━━━━━━━━━ 343s 8s/step - accuracy: 0.3029 - loss: 3.5998 - val_accuracy: 0.3333 - val_loss: 1.1104
Epoch 2/10
42/42 ━━━━━━━━━━━━━━━━━━━━ 281s 7s/step - accuracy: 0.3346 - loss: 1.1040 - val_accuracy: 0.3333 - val_loss: 1.1031
Epoch 3/10
42/42 ━━━━━━━━━━━━━━━━━━━━ 276s 7s/step - accuracy: 0.3479 - loss: 1.1009 - val_accuracy: 0.3333 - val_loss: 1.0996
Epoch 4/10
42/42 ━━━━━━━━━━━━━━━━━━━━ 275s 7s/step - accuracy: 0.3479 - loss: 1.1030 - val_accuracy: 0.3333 - val_loss: 1.1034
Epoch 5/10
42/42 ━━━━━━━━━━━━━━━━━━━━ 403s 10s/step - accuracy: 0.3489 - loss: 1.1019 - val_accuracy: 0.3333 - val_loss: 1.0976
Epoch 6/10
42/42 ━━━━━━━━━━━━━━━━━━━━ 246s 6s/step - accuracy: 0.3469 - loss: 1.1021 - val_accuracy: 0.3333 - val_loss: 1.1006
Epoch 7/10
42/42 ━━━━━━━━━━━━━━━━━━━━ 209s 5s/step - accuracy: 0.3411 - loss: 1.1002 - val_accuracy: 0.3333 - val_loss: 1.0989
Epoch 8/10
42/42 ━━━━━━━━━━━━━━━━━━━━ 204s 5s/step - accuracy: 0.3399 - loss: 1.1001 - val_accuracy: 0.3333 - 

#model evaluation

In [20]:
train_loss,train_acc = model.evaluate(training_set)

42/42 ━━━━━━━━━━━━━━━━━━━━ 46s 1s/step - accuracy: 0.3439 - loss: 1.0991


[1.0986007452011108, 0.3464447855949402]

In [21]:
val_loss,val_acc = model.evaluate(validation_set)

2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 850ms/step - accuracy: 0.3368 - loss: 1.0986


In [25]:
#saving model
model.save("D:/sudesh/projects/plant desies detection/archive (4)/train_model.keras")

In [26]:
# recording history
import json
with open("D:/sudesh/projects/plant desies detection/archive (4)/training.json","w") as f:
    json.dump(training_history.history,f)

In [27]:
#accuracy score
test_set = tf.keras.utils.image_dataset_from_directory(
    "D:/sudesh/projects/plant desies detection/archive (4)/Validation/Validation",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 60 files belonging to 3 classes.


In [37]:
class_name = validation_set.class_names
class_name

['Healthy', 'Powdery', 'Rust']

In [28]:
y_pred=model.predict(test_set)
y_pred

2/2 ━━━━━━━━━━━━━━━━━━━━ 29s 6s/step


array([[0.34425014, 0.32173538, 0.33401448],
       [0.34812146, 0.31373522, 0.33814326],
       [0.35345066, 0.3131393 , 0.33341   ],
       [0.34626696, 0.32267863, 0.33105436],
       [0.3539406 , 0.31071815, 0.3353413 ],
       [0.34628993, 0.31452206, 0.33918792],
       [0.350772  , 0.31135452, 0.3378735 ],
       [0.3488247 , 0.31471488, 0.33646038],
       [0.34811658, 0.3150713 , 0.33681214],
       [0.34855554, 0.31940773, 0.3320367 ],
       [0.3545832 , 0.31371966, 0.33169717],
       [0.34626797, 0.31710863, 0.33662346],
       [0.3494015 , 0.31493804, 0.33566046],
       [0.35469702, 0.31450865, 0.33079433],
       [0.35071477, 0.3142081 , 0.33507717],
       [0.3561948 , 0.3119126 , 0.33189264],
       [0.35331148, 0.3127427 , 0.33394584],
       [0.34681666, 0.32030684, 0.3328765 ],
       [0.3534731 , 0.3173385 , 0.32918838],
       [0.3553531 , 0.31012037, 0.33452654],
       [0.34538954, 0.31950864, 0.33510178],
       [0.35271156, 0.31466997, 0.33261847],
       [0.

In [29]:
pred_categori=tf.argmax(y_pred,axis=1)
pred_categori

<tf.Tensor: shape=(60,), dtype=int64, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)>

In [30]:
true_categori=tf.concat([y for x,y in test_set],axis=0)
true_categori

<tf.Tensor: shape=(60, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
      

In [31]:
y_true=tf.argmax(true_categori,axis=1)
y_true

<tf.Tensor: shape=(60,), dtype=int64, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)>

In [38]:
from sklearn.metrics import classification_report, confusion_matrix
classification_report(y_true,pred_categori,target_names=class_name)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


'              precision    recall  f1-score   support\n\n     Healthy       0.33      1.00      0.50        20\n     Powdery       0.00      0.00      0.00        20\n        Rust       0.00      0.00      0.00        20\n\n    accuracy                           0.33        60\n   macro avg       0.11      0.33      0.17        60\nweighted avg       0.11      0.33      0.17        60\n'

In [39]:
cn=confusion_matrix(y_true,pred_categori)
cn

array([[20,  0,  0],
       [20,  0,  0],
       [20,  0,  0]], dtype=int64)